export const ALL_COUPON_REQUEST ="ALL_COUPON_REQUEST";
export const ALL_COUPON_SUCCESS ="ALL_COUPON_SUCCESS";
export const ALL_COUPON_FAIL ="ALL_COUPON_FAIL";


// Delete COUPON
export const  DELETE_COUPON_REQUEST ="DELETE_COUPON_REQUEST";
export const  DELETE_COUPON_SUCCESS ="DELETE_COUPON_SUCCESS";
export const  DELETE_COUPON_FAIL ="DELETE_COUPON_FAIL";
export const  DELETE_COUPON_RESET ="DELETE_COUPON_RESET";







// COUPON details
export const COUPON_DETAILS_REQUEST ="ALL_COUPON_REQUEST";
export const COUPON_DETAILS_SUCCESS ="ALL_COUPON_SUCCESS";
export const COUPON_DETAILS_FAIL ="ALL_COUPON_FAIL";








export const CLEAR_ERRORS ="CLEAR_ERRORS";

