export const REGISTER_SELLER_REQUEST = 'REGISTER_SELLER_REQUEST'
export const REGISTER_SELLER_SUCCESS = 'REGISTER_SELLER_SUCCESS'
export const REGISTER_SELLER_FAIL = 'REGISTER_SELLER_FAIL'

export const LOGIN_REQUEST ="LOGIN_REQUEST";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_FAIL ="LOGIN_FAIL";

export const LOGOUT_SUCCESS ="LOGOUT_SUCCESS";
export const LOGOUT_FAIL ="LOGOUT_FAIL";

export const LOAD_SELLER_REQUEST ="LOAD_SELLER_REQUEST";
export const LOAD_SELLER_SUCCESS ="LOAD_SELLER_SUCCESS";
export const LOAD_SELLER_FAIL ="LOAD_SELLER_FAIL";



export const CLEAR_ERRORS ="CLEAR_ERRORS";
